### ISSUE TITLE
Mod hides all clouds

### ISSUE THREAD

**Issue by DoctorVanGogh** [xxmicloxx/VolumetricShading#1]
With this mod active - no matter the setting - the game does not render **any** clouds:

VolumetricShading disabled (in ModManager):
![2021-03-28_15-58-31](https://user-images.githubusercontent.com/324067/112754938-c1b04b00-8fde-11eb-854e-c5380456161f.png)

VolumetricShading enabled (in ModManager):
![2021-03-28_15-57-33](https://user-images.githubusercontent.com/324067/112754954-d7be0b80-8fde-11eb-9f6e-9b215df91a26.png)

**Comment by xxmicloxx** [comment]
Hello, sorry about that. I just uploaded a new version to the mod portal which should fix the problem (v0.5.1). Can you please try and report back if it works? Thank you very much!

**Comment by DoctorVanGogh** [comment]
Yep... 0.5.1 has clouds again

![2021-03-29_09-37-21](https://user-images.githubusercontent.com/324067/112802624-b149b000-9072-11eb-963b-7d188ba153a3.png)

Alas.... #2 :(
